version: '3.8'

services:
  # === ІНФРАСТРУКТУРА .NET МОНОЛІТУ ===
  cinema-db:
    image: pgvector/pgvector:pg16
    container_name: cinema-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: cinema_local_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cinema-redis:
    image: redis:alpine
    container_name: cinema-redis
    command: redis-server --requirepass redis_password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Спільний брокер для .NET та NestJS!
  cinema-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: cinema-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  # === ІНФРАСТРУКТУРА NESTJS МІКРОСЕРВІСУ ===
  loyalty-db:
    image: postgres:15-alpine
    container_name: cinema_loyalty_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cinema_loyalty_db
    ports:
      - "5433:5432"
    volumes:
      - loyalty_pg_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redis_data:
  loyalty_pg_data: