<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cinema.Booking.Application\Cinema.Booking.Application.csproj" />
    <PackageReference Include="Polly.Core" />
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>
</Project>
