<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TngTech.ArchUnitNET.xUnitV3" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Host\Cinema.Api\Cinema.Api.csproj" />
    <ProjectReference Include="..\..\src\Cinema.Application\Cinema.Application.csproj" />
    <ProjectReference Include="..\..\src\Cinema.Domain\Cinema.Domain.csproj" />
    <ProjectReference Include="..\..\src\Cinema.Infrastructure\Cinema.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Catalog\Cinema.Catalog.Domain\Cinema.Catalog.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Catalog\Cinema.Catalog.Application\Cinema.Catalog.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Catalog\Cinema.Catalog.Infrastructure\Cinema.Catalog.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Scheduling\Cinema.Scheduling.Domain\Cinema.Scheduling.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Scheduling\Cinema.Scheduling.Application\Cinema.Scheduling.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Scheduling\Cinema.Scheduling.Infrastructure\Cinema.Scheduling.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Booking\Cinema.Booking.Application\Cinema.Booking.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Booking\Cinema.Booking.Infrastructure\Cinema.Booking.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Orders\Cinema.Orders.Application\Cinema.Orders.Application.csproj" />
  </ItemGroup>

</Project>
